ARG GRADLE_CLI_OPTS=''

FROM gradle:7.1.1-jdk11 AS build
COPY ./keycloak-customisation /keycloak-customisation
WORKDIR /keycloak-customisation
RUN gradle clean jar

FROM jboss/keycloak:16.1.0 AS run

# DEV THEME KC: commenter la ligne ci-dessous
#COPY --from=build theme-pass-emploi /opt/jboss/keycloak/themes/theme-pass-emploi
#COPY --from=build theme-pass-emploi-web /opt/jboss/keycloak/themes/theme-pass-emploi-web
#COPY --from=build theme-pass-emploi-app /opt/jboss/keycloak/themes/theme-pass-emploi-app
COPY --from=build keycloak-customisation/build/libs/pass-emploi-keycloak-customisation-0.0.1-SNAPSHOT.jar /opt/jboss/keycloak/standalone/deployments/pass-emploi-keycloak-customisation.jar
COPY bin/elastic-apm-agent-1.29.0.jar /usr/bin/elastic-apm-agent.jar
COPY bin/custom-startup-scripts /opt/jboss/custom-startup-scripts
COPY bin/startup-scripts /opt/jboss/startup-scripts
COPY turbo-kc/standalone.xml /opt/jboss/keycloak/standalone/configuration
COPY turbo-kc/docker-entrypoint.sh /usr/bin/
#
#ENV KEYCLOAK_CONTEXT_PATH="auth"
ENV JBOSS_NODE_NAME="keycloak"
ENV DISABLE_CLUSTER_MODE="false"
#HTTP
EXPOSE 8080
#TCP JGROUP FOR CLUSTERING DISCOVERY
EXPOSE 7600
#TCP JGROUP_FD FOR CLUSTERING DISCOVERY
EXPOSE 57600
ENTRYPOINT ["/usr/bin/docker-entrypoint.sh"]
CMD ["/opt/jboss/tools/docker-entrypoint.sh", "-b", "0.0.0.0"]
